### ISSUE TITLE
pipe2 causes crash on macOS

### ISSUE THREAD

**Issue by corasaurus-hex** [andrewchambers/janet-posix-spawn#1]
posix-spawn is using pipe2 here: https://github.com/andrewchambers/janet-posix-spawn/blob/master/posix-spawn.c#L473

Unfortunately this isn't available on macOS (and [maybe others?](https://www.gnu.org/software/gnulib/manual/html_node/pipe2.html)).

Would be ok to change this to pipe instead? I couldn't find pipe2 in the POSIX standard but maybe I'm looking in the wrong place, but if it's not in the standard it might hold more with the spirit of the library to not include it anyways.

Thanks!

**Comment by andrewchambers** [comment]
The problem is pipe is essentially race condition in multi threaded programs.

We should probably fall back to using pipe if pipe2 isn't present though.

**Comment by corasaurus-hex** [comment]
Yeah the race condition sucks, but I guess this is tolerable alternative for the moment. Should we add a warning?

**Comment by Deepansharora27** [comment]
Just Following up, is pipe(2) available for Mac OS Now ?
